
#ifndef __EXTPROFILE_TBB_H__
#define __EXTPROFILE_TBB_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_tbb.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline void x_parallel_for(int64 start, int64 end, CVarRef func, int64 blocksize = -1) {
  FUNCTION_INJECTION_BUILTIN(parallel_for);
  f_parallel_for(start, end, func, blocksize);
}

inline Variant x_parallel_for_array(CVarRef arraydata, CVarRef func, int64 blocksize = -1) {
  FUNCTION_INJECTION_BUILTIN(parallel_for_array);
  return f_parallel_for_array(arraydata, func, blocksize);
}

inline Array x_concurrent_globals() {
  FUNCTION_INJECTION_BUILTIN(concurrent_globals);
  return f_concurrent_globals();
}

inline Variant x_parallel_reduce(CVarRef data, CVarRef workerfunction, CVarRef initialvalue, CVarRef joinfunction = null_variant) {
  FUNCTION_INJECTION_BUILTIN(parallel_reduce);
  return f_parallel_reduce(data, workerfunction, initialvalue, joinfunction);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_TBB_H__
